### PR TITLE
hello world script

### PR DESCRIPTION
**Pull request by brendaokumu**

### CODE REVIEW

**Comment by brendaokumu** [comment]
hello world script require review

**Review by Ritika-Agrawal811 — COMMENTED** [review]
why have you used prompt()?

**Comment by brendaokumu** [comment]
For interactivity purposes with the user.. I remove them?

**Review by Ritika-Agrawal811 — COMMENTED** [review]
you are supposed to write your details.

**Comment by brendaokumu** [comment]
review request after changes

**Review by Ritika-Agrawal811 — COMMENTED** [review]
use console.log() instead of alert()

**Comment by brendaokumu** [comment]
request review after changes

**Review by ifatoki — APPROVED** [review]

**Pull request merged**
