### PR TITLE
commit from rugue

### PR DESCRIPTION
**Pull request by rugue**

### CODE REVIEW

**Comment by rugue** [comment]
second commit, edited myName

**Review by McToluene — CHANGES_REQUESTED** [review]
Please your HNG-ID should include HNG characters. For example HNG-1234

**Review by melissaugrai — CHANGES_REQUESTED** [review]
The myID needs to be changed to "HNG-04167".

**Comment by rugue** [comment]
Thanks for the feedback guys

**Review by melissaugrai — APPROVED** [review]

**Review by melissaugrai — APPROVED** [review]

**Review by melissaugrai — APPROVED** [review]

**Review by McToluene — APPROVED** [review]

**Pull request merged**
