### PR TITLE
https://github.com/SarahAnym/hng-wonderwoman-task-1

### PR DESCRIPTION
**Pull request by SarahAnym**

### CODE REVIEW

**Comment by devhalimah** [comment]
There's nothing to merge
Your script is empty

**Review by SarahAnym — COMMENTED** [review]
Made a mistake not adding the script (instructions).

**Review by SarahAnym — COMMENTED** [review]
Made a mistake not adding the scripts

**Review by Mahalinoro — CHANGES_REQUESTED** [review]
Hello, kindly review your code because it has PHP in it while it sais that it is a python file. Also please follow the filename normal [ID]-[slackusername].py and make sure you are in the develop branch

**Pull request closed without merging**
