### PR TITLE
06605-ameliaoneh

### PR DESCRIPTION
**Pull request by miah222222**

### CODE REVIEW

**Review by Mahalinoro — CHANGES_REQUESTED** [review]
Please review your output. It should follow this format => Hello World, this is [full name] with HNGi7 ID [ID] using [language] for stage 2 task [email_address]
eg. => Hello World, this is Itunuloluwa Fatoki with HNGi7 ID HNG-01234 using javascript for stage 2 task itunuworks@gmail.com

**Comment by miah222222** [comment]
I have reviewed the output and its seem okay.
Thanks

**Review by Mahalinoro — CHANGES_REQUESTED** [review]
Please review your output: 
like this as an example =>  Hello World, this is Itunuloluwa Fatoki with HNGi7 ID HNG-01234 using javascript for stage 2 task itunuworks@gmail.com

**Review by miah222222 — COMMENTED** [review]
I have inputed the necessary changes to the file.

**Review by Mahalinoro — APPROVED** [review]
Reviewed!

**Pull request merged**
