### PR TITLE
Hngi7 task 2 

### PR DESCRIPTION
**Pull request by greatkene**

### CODE REVIEW

**Review by lindaokorie27 — CHANGES_REQUESTED** [review]
Please delete the files you created named "Great-droid"

**Review by tosinibrahim96 — APPROVED** [review]
LGTM

**Review by tosinibrahim96 — APPROVED** [review]

**Review by Mahalinoro — CHANGES_REQUESTED** [review]
Please change "world" to "World"

**Comment by greatkene** [comment]
MAde change to file

**Review by Mahalinoro — APPROVED** [review]
Reviewed!

**Pull request merged**
