### PR TITLE
please merge my script 

### PR DESCRIPTION
**Pull request by tiarayuppy**

### CODE REVIEW

**Review by Mahalinoro — CHANGES_REQUESTED** [review]
Please there is an error in your output the email variable is not defined

**Comment by tiarayuppy** [comment]
Oops, let me fix

**Comment by tiarayuppy** [comment]
Hello @Mahalinoro error fixed

**Review by Mahalinoro — CHANGES_REQUESTED** [review]
One last thing: the output should follow this format be like this:
Hello World, this is Itunuloluwa Fatoki with HNGi7 ID HNG-01234 using javascript for stage 2 task itunuworks@gmail.com

**Comment by tiarayuppy** [comment]
You are right

**Comment by tiarayuppy** [comment]
Done 😊

**Review by Mahalinoro — CHANGES_REQUESTED** [review]
Sorry to bother you but, please change "world" to "World" and remove the extra spaces after "stage"  because the output has a newline

**Comment by tiarayuppy** [comment]
Any other thing?

**Comment by tiarayuppy** [comment]
It’s done though, thanks for your patience

**Review by Mahalinoro — APPROVED** [review]
Reviewed!

**Pull request merged**
