### PR TITLE
My script to print hello world...

### PR DESCRIPTION
**Pull request by gbengaoj**

### CODE REVIEW

**Review by ifatoki — CHANGES_REQUESTED** [review]
Hi Gbenga, what you have here is a binary file. 
Can you please upload your raw python script?

**Review by McToluene — CHANGES_REQUESTED** [review]
File not showing because it was in a binary format

**Comment by gbengaoj** [comment]
> Hi Gbenga, what you have here is a binary file.
> Can you please upload your raw python script?

I have done that. Thanks.

**Comment by gbengaoj** [comment]
> File not showing because it was in a binary format

I have resolved it. Thank you.

**Review by McToluene — APPROVED** [review]

**Review by melissaugrai — APPROVED** [review]

**Review by melissaugrai — APPROVED** [review]

**Review by ifatoki — APPROVED** [review]

**Pull request merged**
