### PR TITLE
Create 06527-gracehalliday.py

### PR DESCRIPTION
**Pull request by peggylicious97**
name ="grace halliday"
Hngid="HNG-06527"
email="gracehally7@gmail.com"
Print("Hello World, this is ", name,"with HNGi7 ID", Hngid,"using python for stage 2 task", email)

### CODE REVIEW

**Comment by peggylicious97** [comment]
Pls review agin

**Review by onedebos — CHANGES_REQUESTED** [review]
Please follow the format required.

**Review by Mahalinoro — CHANGES_REQUESTED** [review]
Please correct the format for the output as well as how to write print()

**Review by Mahalinoro — APPROVED** [review]
Reviewed!

**Review by onedebos — APPROVED** [review]

**Review by peggylicious97 — COMMENTED** [review]
I want to change HNG ID to HNGi7 ID

**Pull request merged**
