### PR TITLE
Task completed

### PR DESCRIPTION
**Pull request by abu4kind**
Hello, This Abubakar Adamu's task one for team Wonderwoman on HNG7i. 

Looking forward to your feedback.

Slack username: @abu4kind

### CODE REVIEW

**Review by lindaokorie27 — CHANGES_REQUESTED** [review]
There are two files you created, one has the right file name amd is empty while the other doesn't have the right file name and has your code in it. Also look at your hng borad and get your ID, there shouldn't be a "u" in the id.

**Comment by abu4kind** [comment]
> There are two files you created, one has the right file name amd is empty while the other doesn't have the right file name and has your code in it. Also look at your hng borad and get your ID, there shouldn't be a "u" in the id.

Please which one is correct and how do i go back and delete the wrong one

**Comment by abu4kind** [comment]
and also make the necessary adjustment can you help with the steps

**Comment by abu4kind** [comment]
Many thanks

**Comment by lindaokorie27** [comment]
scripts/HNG-00030-abu4kind.js This filename is correct. Put your script in this file and delete the other file. The ID in this filename is what you should use in the sentence too.

**Review by lindaokorie27 — COMMENTED** [review]
You still haven't made the changes. Visit [here](https://hngi7-wonderwoman-task2.herokuapp.com/) and look at the format of others. Then delete two files you made. You should have only one file

**Pull request closed without merging**
