### PR TITLE
adding my script

### PR DESCRIPTION
**Pull request by Emidowojo**

### CODE REVIEW

**Review by melissaugrai — CHANGES_REQUESTED** [review]
Your script looks great. Please rename the file to ------>    04704-aimeee.js

**Comment by Emidowojo** [comment]
@Teddiurssa I have renamed my file name. Thank you

**Comment by sholance** [comment]
Also, assign the variable email to email before printing

**Comment by lindaokorie27** [comment]
There is a second file created by you. The name is Aimeee.js, delete that and you are good.

**Comment by Emidowojo** [comment]
@sholance @LindieK I've done them both. thank you

**Review by melissaugrai — APPROVED** [review]

**Pull request merged**
