### PR TITLE
stage two task

### PR DESCRIPTION
**Pull request by ibraheemosule**

### CODE REVIEW

**Review by melissaugrai — CHANGES_REQUESTED** [review]
Just a little typo your `myHngID = "SNG-02962"` need to change to "HNG-02962"

**Comment by ibraheemosule** [comment]
But (SNG-02962) is the ID i saw on my HNG board.
Attaches to this mail is the screenshot proof

**Comment by lindaokorie27** [comment]
Ok will let the team leaders know about that. Were you part of start.ng?

**Comment by ibraheemosule** [comment]
Yes I was.

**Review by melissaugrai — APPROVED** [review]

**Pull request merged**
