### PR TITLE
Create Daniella.py

### PR DESCRIPTION
**Pull request by Daniellaamba**

### CODE REVIEW

**Review by Mahalinoro — CHANGES_REQUESTED** [review]
Please follow this format 
=> Hello World, this is Itunuloluwa Fatoki with HNGi7 ID HNG-01234 using javascript for stage 2 task itunuworks@gmail.com

**Comment by sholance** [comment]
Your variable naming is wrong, instead of (First name &Last Name) use "name". The word "id" is supposed to be in small letters.

**Comment by Daniellaamba** [comment]
Thank you, I will effect the changes and re send

**Comment by Daniellaamba** [comment]
Please, do I have to request pull after effecting the changes?

**Review by Mahalinoro — APPROVED** [review]
Reviewed!

**Comment by Daniellaamba** [comment]
Thank you, please how do I check my status, if passed or fail?

**Pull request merged**
