### PR TITLE
Create Vikas.php

### PR DESCRIPTION
**Pull request by VikasRathore162**

### CODE REVIEW

**Review by lindaokorie27 — CHANGES_REQUESTED** [review]
Add your ID to your file name like so "00296-Vikas.php"

**Comment by VikasRathore162** [comment]
I didn't get this. Can you give me some example how to do this or some more
help.
Please  it's a request.

**Comment by lindaokorie27** [comment]
How you would name the file in your case would be 00296-Vikas.php . Exactly like that.

**Comment by VikasRathore162** [comment]
So is it correct??

**Review by melissaugrai — CHANGES_REQUESTED** [review]
The filename needs to say ------>00296-vikas.php
Need to add email to the end of output phrase, please -----> add email after the word task.
`echo("Hello World, this is " . $name. " with HNGi7 ID " .$id. " using " .$language . " for stage 2 task");`

**Comment by lindaokorie27** [comment]
I think you reated a new PR. Saw your name yesterday, please close this

**Pull request closed without merging**
