### PR TITLE
feature: added script

### PR DESCRIPTION
**Pull request by TheKachi**
I've added a file to the scripts folder. Kindly review.

### CODE REVIEW

**Review by melissaugrai — CHANGES_REQUESTED** [review]
Need to have your email at the end of your output message

**Comment by TheKachi** [comment]
> Need to have your email at the end of your output message

Thanks @Teddiurssa I've added email, kindly review.

**Review by melissaugrai — CHANGES_REQUESTED** [review]
`My email is ${myEmail}.`  remove My email is ---> keep email variable

**Comment by TheKachi** [comment]
Good morning. 
Please review @Teddiurssa thanks

**Review by Mahalinoro — CHANGES_REQUESTED** [review]
Hello, please remove the dot after task.

**Comment by TheKachi** [comment]
> Hello, please remove the dot after task.

i have done that now. please review

**Review by Mahalinoro — APPROVED** [review]
Reviewed!

**Pull request merged**
