### PR TITLE
Added email address 

### PR DESCRIPTION
**Pull request by amadikwajoyn**
I just added an email address in the task 2.

### CODE REVIEW

**Review by lindaokorie27 — CHANGES_REQUESTED** [review]
Please remove all form of html, put the email at the end of the string and echo only one string

**Review by devhalimah — CHANGES_REQUESTED** [review]
Please remove the third name
Just two names is required

**Review by devhalimah — CHANGES_REQUESTED** [review]
Add email address

**Comment by amadikwajoyn** [comment]
Removed the html tags

**Comment by amadikwajoyn** [comment]
Please merge my Request from sweetheart

**Review by Mahalinoro — CHANGES_REQUESTED** [review]
There is a syntax error. You forgot to add ";" after your email.

**Review by Mahalinoro — APPROVED** [review]
Reviewed!

**Comment by amadikwajoyn** [comment]
I removed semi colon

**Review by devhalimah — APPROVED** [review]

**Review by devhalimah — APPROVED** [review]

**Pull request merged**
